name: run_pipe
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Train and test model(pipe)
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          TB_CREDENTIALS: ${{ secrets.TB_CREDENTIALS }}
        run: |
          echo "test run pipeline"
          # Your ML workflow goes here
          dvc pull anchors.csv --run-cache
          dvc pull test.csv --run-cache
          pip install -r requirements.txt
          # Start tensorboard and train
          # echo "## header" > report.md
          # cml-tensorboard-dev --logdir logs --md --name "Go to tensorboard" >> report.md
          # cml-send-comment report.md
          dvc repro
          echo "## Model train metrics" > report1.md
          cat metrics.csv >> report1.md
          echo "## Model test metrics<br />" >> report1.md
          cat test_metrics.csv >> report1.md
          cml-send-comment report1.md